package com.vernai.ai.parser

import com.vernai.domain.model.letter.LetterInput
import com.vernai.domain.model.letter.SignaturePlaceholders
import com.vernai.domain.model.letter.StructuredLetter
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

@Serializable
data class RawLetterJson(
    val subject: String? = null,
    val salutation: String? = null,
    val reference: String? = null,
    val context_paragraph: String? = null,
    val factual_details_paragraph: String? = null,
    val requested_action_paragraph: String? = null,
    val closing: String? = null,
    val signature_name_placeholder: String? = null,
    val place: String? = null,
    val date: String? = null,
    val english_subject: String? = null,
    val english_body: String? = null,
    val preserved_facts: List<String>? = null
)

/**
 * Domain exceptions representing specific failure points during LLM output parsing and schema validation.
 */
sealed class LetterParsingException(message: String, cause: Throwable? = null) : Exception(message, cause) {
    class MalformedJson(val rawOutput: String, cause: Throwable) :
        LetterParsingException("Model output could not be parsed as valid JSON: ${cause.message}", cause)

    class SchemaValidationFailed(val validationErrors: List<String>, val rawOutput: String) :
        LetterParsingException("Schema validation failed with errors: ${validationErrors.joinToString("; ")}")

    class FactPreservationViolation(val missingFacts: List<String>, val rawOutput: String) :
        LetterParsingException("Anti-hallucination check failed; user facts missing: ${missingFacts.joinToString("; ")}")
}

/**
 * Parser and Schema Validator for structured Telugu civic letters generated by local LLMs.
 */
class TeluguLetterParser {

    private val json = Json {
        ignoreUnknownKeys = true
        isLenient = true
        coerceInputValues = true
    }

    /**
     * Strictly parses and validates LLM raw response.
     * Throws [LetterParsingException] if the output is malformed, lacks required fields, or violates anti-hallucination rules.
     */
    @Throws(LetterParsingException::class)
    fun parseOrThrow(rawOutput: String, input: LetterInput): StructuredLetter {
        val cleanJson = extractJsonSubstring(rawOutput)
        if (cleanJson.isBlank() || cleanJson == "{}") {
            throw LetterParsingException.MalformedJson(rawOutput, IllegalArgumentException("Empty or missing JSON block"))
        }

        val rawLetter: RawLetterJson = try {
            json.decodeFromString<RawLetterJson>(cleanJson)
        } catch (e: Throwable) {
            throw LetterParsingException.MalformedJson(rawOutput, e)
        }

        // 1. Schema Validation
        val validationErrors = mutableListOf<String>()

        val subject = rawLetter.subject?.trim().orEmpty()
        if (subject.isBlank()) {
            validationErrors.add("Missing or empty 'subject' field")
        }

        val salutation = rawLetter.salutation?.trim().orEmpty()
        if (salutation.isBlank()) {
            validationErrors.add("Missing or empty 'salutation' field")
        }

        val contextPara = rawLetter.context_paragraph?.trim().orEmpty()
        val factsPara = rawLetter.factual_details_paragraph?.trim().orEmpty()
        val actionPara = rawLetter.requested_action_paragraph?.trim().orEmpty()

        if (contextPara.isBlank() && factsPara.isBlank()) {
            validationErrors.add("At least one descriptive body paragraph ('context_paragraph' or 'factual_details_paragraph') must be provided")
        }

        if (actionPara.isBlank()) {
            validationErrors.add("Missing or empty 'requested_action_paragraph' specifying the relief/action requested")
        }

        val closing = rawLetter.closing?.trim().orEmpty()
        if (closing.isBlank()) {
            validationErrors.add("Missing or empty 'closing' field")
        }

        if (validationErrors.isNotEmpty()) {
            throw LetterParsingException.SchemaValidationFailed(validationErrors, rawOutput)
        }

        // 2. Anti-Hallucination and Fact Preservation Validation
        val bodyTextCombined = listOf(contextPara, factsPara, actionPara).joinToString(" ")
        val preservedFacts = rawLetter.preserved_facts ?: input.userProvidedFacts

        val missingFacts = input.userProvidedFacts.filter { fact ->
            val keywords = fact.split(" ").filter { it.length > 3 }
            if (keywords.isNotEmpty()) {
                // At least some significant keywords or the fact itself must appear
                keywords.none { keyword -> bodyTextCombined.contains(keyword, ignoreCase = true) } &&
                        (rawLetter.preserved_facts == null || !rawLetter.preserved_facts.any { it.contains(fact, ignoreCase = true) })
            } else {
                false
            }
        }

        // If user provided facts but model failed to incorporate them completely, flag it
        if (input.userProvidedFacts.isNotEmpty() && missingFacts.size == input.userProvidedFacts.size) {
            throw LetterParsingException.FactPreservationViolation(missingFacts, rawOutput)
        }

        // 3. Assemble placeholders and structured fields
        val place = rawLetter.place?.trim()?.ifBlank { null }
            ?: input.location
            ?: "[ప్రదేశం/గ్రామం]"

        val date = rawLetter.date?.trim()?.ifBlank { null }
            ?: input.date
            ?: "[తేదీ: DD-MM-YYYY]"

        val applicantName = rawLetter.signature_name_placeholder?.trim()?.ifBlank { null }
            ?: input.applicantName
            ?: "[దరఖాస్తుదారుడి పేరు]"

        val signaturePlaceholders = SignaturePlaceholders(
            applicantName = applicantName,
            signatureLine = "[దరఖాస్తుదారుడి సంతకం]",
            location = place,
            date = date,
            contactPlaceholder = "[ఫోన్ నంబర్ / చిరునామా]"
        )

        val bodyParagraphs = listOfNotNull(
            contextPara.ifBlank { null },
            factsPara.ifBlank { null },
            actionPara.ifBlank { null }
        )

        val fullTeluguBody = renderFullTeluguLetter(
            date = date,
            place = place,
            recipient = input.recipient,
            subject = subject,
            reference = rawLetter.reference,
            salutation = salutation,
            bodyParagraphs = bodyParagraphs,
            closing = closing,
            signature = signaturePlaceholders
        )

        val englishTranslation = rawLetter.english_body?.trim()?.ifBlank { null }
            ?: buildDefaultEnglishTranslation(input, subject, bodyParagraphs)

        return StructuredLetter(
            letterType = input.letterType,
            recipient = input.recipient,
            place = place,
            date = date,
            salutation = salutation,
            subject = subject,
            reference = rawLetter.reference?.trim()?.ifBlank { null },
            bodyParagraphs = bodyParagraphs,
            formalTeluguLetterBody = fullTeluguBody,
            closing = closing,
            signaturePlaceholders = signaturePlaceholders,
            preservedFacts = preservedFacts,
            englishTranslation = englishTranslation
        )
    }

    /**
     * Resilient parse: validates model output, falling back to a deterministic,
     * hallucination-free template if the model emits corrupted or invalid output.
     */
    fun parseWithFallback(rawOutput: String, input: LetterInput): StructuredLetter {
        return try {
            parseOrThrow(rawOutput, input)
        } catch (e: LetterParsingException) {
            buildDeterministicFallback(input)
        }
    }

    /**
     * Deterministic, zero-hallucination fallback letter generated strictly from the user's inputs.
     */
    fun buildDeterministicFallback(input: LetterInput): StructuredLetter {
        val place = input.location ?: "[ప్రదేశం/గ్రామం]"
        val date = input.date ?: "[తేదీ: DD-MM-YYYY]"
        val applicantName = input.applicantName ?: "[దరఖాస్తుదారుడి పేరు]"

        val subject = "${input.letterType.defaultSubjectPrefix}${input.teluguVoiceTranscript.take(40)} గురించి."
        val salutation = "గౌరవనీయులైన ${input.recipient.designation} గారికి,"

        val contextPara = "విన్నవించునది ఏమనగా, నేను/మేము పై పేర్కొన్న ప్రాంతానికి చెందిన నివాసితులము. ప్రస్తుత సమస్యపై మీ దృష్టికి తీసుకురావడానికి ఈ ${input.letterType.teluguTitle} సమర్పిస్తున్నాము."

        val factsDetails = if (input.userProvidedFacts.isNotEmpty()) {
            "ఈ క్రింది వాస్తవాలను మీ పరిశీలనకు ఉంచుతున్నాము:\n" +
                    input.userProvidedFacts.mapIndexed { index, fact -> "${index + 1}. $fact" }.joinToString("\n")
        } else {
            "సమస్య వివరాలు:\n${input.teluguVoiceTranscript}"
        }

        val actionPara = "కావున దయచేసి పై పేర్కొన్న విషయాలను పరిశీలించి, వెంటనే తగిన విచారణ జరిపి తగు పరిష్కారం కల్పించవలసిందిగా కోరుచున్నాము."
        val closing = "ఇట్లు,\nభవదీయుడు/భవదీయురాలు,"

        val signaturePlaceholders = SignaturePlaceholders(
            applicantName = applicantName,
            signatureLine = "[దరఖాస్తుదారుడి సంతకం]",
            location = place,
            date = date
        )

        val bodyParagraphs = listOf(contextPara, factsDetails, actionPara)
        val fullTeluguBody = renderFullTeluguLetter(
            date = date,
            place = place,
            recipient = input.recipient,
            subject = subject,
            reference = null,
            salutation = salutation,
            bodyParagraphs = bodyParagraphs,
            closing = closing,
            signature = signaturePlaceholders
        )

        val englishTranslation = buildDefaultEnglishTranslation(input, subject, bodyParagraphs)

        return StructuredLetter(
            letterType = input.letterType,
            recipient = input.recipient,
            place = place,
            date = date,
            salutation = salutation,
            subject = subject,
            reference = null,
            bodyParagraphs = bodyParagraphs,
            formalTeluguLetterBody = fullTeluguBody,
            closing = closing,
            signaturePlaceholders = signaturePlaceholders,
            preservedFacts = input.userProvidedFacts,
            englishTranslation = englishTranslation
        )
    }

    /**
     * Renders standard administrative Telugu letter layout with official alignment and styling.
     */
    private fun renderFullTeluguLetter(
        date: String,
        place: String,
        recipient: com.vernai.domain.model.letter.LetterRecipient,
        subject: String,
        reference: String?,
        salutation: String,
        bodyParagraphs: List<String>,
        closing: String,
        signature: SignaturePlaceholders
    ): String {
        return buildString {
            appendLine("స్థలం: $place")
            appendLine("తేదీ: $date")
            appendLine()
            appendLine("స్వీకర్త:")
            appendLine("$salutation")
            appendLine("${recipient.departmentOrOffice},")
            if (recipient.officeAddress.isNotBlank()) {
                appendLine("${recipient.officeAddress}.")
            }
            appendLine()
            appendLine(subject)
            if (!reference.isNullOrBlank()) {
                appendLine("సందర్భం: $reference")
            }
            appendLine()
            appendLine("ఆర్యా,")
            appendLine()
            bodyParagraphs.forEach { para ->
                appendLine(para)
                appendLine()
            }
            appendLine("ధన్యవాదములతో,")
            appendLine()
            appendLine(closing)
            appendLine(signature.signatureLine)
            appendLine("(${signature.applicantName})")
            if (signature.location.isNotBlank()) {
                appendLine("చిరునామా: ${signature.location}")
            }
            appendLine(signature.contactPlaceholder)
        }.trimEnd()
    }

    private fun buildDefaultEnglishTranslation(
        input: LetterInput,
        subject: String,
        bodyParagraphs: List<String>
    ): String {
        return buildString {
            appendLine("To")
            appendLine("The ${input.recipient.designation},")
            appendLine("${input.recipient.departmentOrOffice}.")
            if (input.recipient.officeAddress.isNotBlank()) {
                appendLine(input.recipient.officeAddress)
            }
            appendLine()
            appendLine("Subject: Official ${input.letterType.englishTitle} regarding ${input.teluguVoiceTranscript.take(40)}")
            appendLine()
            appendLine("Respected Sir/Madam,")
            appendLine()
            appendLine("I am submitting this formal ${input.letterType.englishTitle.lowercase()} regarding the following matter:")
            if (input.userProvidedFacts.isNotEmpty()) {
                input.userProvidedFacts.forEachIndexed { i, fact ->
                    appendLine("${i + 1}. $fact")
                }
            } else {
                appendLine(input.teluguVoiceTranscript)
            }
            appendLine()
            appendLine("I request your esteemed office to kindly examine the matter and initiate necessary action at the earliest.")
            appendLine()
            appendLine("Yours faithfully,")
            appendLine("${input.applicantName ?: "[Applicant Signature]"}")
            appendLine("Place: ${input.location ?: "[Place]"}")
            appendLine("Date: ${input.date ?: "[Date]"}")
        }.trimEnd()
    }

    private fun extractJsonSubstring(text: String): String {
        val start = text.indexOf('{')
        val end = text.lastIndexOf('}')
        return if (start != -1 && end != -1 && end > start) {
            text.substring(start, end + 1)
        } else {
            ""
        }
    }
}
